### PR TITLE
Add recipe for advsndsw

### PR DESCRIPTION
**Pull request by olantwin**

### CODE REVIEW

**Comment by olantwin** [comment]
Bypassing branch protections since this *cannot* affect other packages.

@dcentanni would be great if you could confirm that this also works for you :)

**Comment by dcentanni** [comment]
Software is building successfully to me but when I load the environment with: `alienv enter advsndsw/latest-main-release` I get:
```
Loading advsndsw/latest-main-release
ERROR: Unable to locate a modulefile for 'FairLogger/-local1'
ERROR: Load of requirement FairLogger/-local1 failed
```
Did I fail on something ?

**Comment by olantwin** [comment]
> Software is building successfully to me but when I load the environment with: `alienv enter advsndsw/latest-main-release` I get:
> 
> ```
> Loading advsndsw/latest-main-release
> ERROR: Unable to locate a modulefile for 'FairLogger/-local1'
> ERROR: Load of requirement FairLogger/-local1 failed
> ```
> 
> Did I fail on something ?

Fixed in #46

**Comment by dcentanni** [comment]
I confirm, it worked. Thanks!

**Pull request merged**
