### PR TITLE
XRootD: Export PKG_ROOT

### LINKED ISSUE #29: XRootD: `XROOTD_ROOT` is not set by module file

### PR DESCRIPTION
**Pull request by olantwin**
Fixes #29

### CODE REVIEW

**Comment by siilieva** [comment]
the env variable XROOTD_ROOT is set in sndsw.sh. Why is it needed to have it also here?
in the sndsw env one has e.g.
echo $XROOTD_ROOT
/cvmfs/sndlhc.cern.ch/SNDLHC-2023/Aug30//sw//slc7_x86-64/XRootD/v5.5.5-local1

**Comment by olantwin** [comment]
1. It's not set for the incremental recipe, so if you do an incremental build (the default, as basically everyone uses sndsw as a development package), the resulting module file can not be loaded due to an unset variable.
2. Would it not be better to set each ENV variable in the relevant package? Of course we can set everything in `sndsw.sh`, but this will result in a big mess. Also, some packages that have XRootD as a dependency might require `$XROOTD_ROOT` being set to find the package. They sometimes fail quietly if they can't find optional dependencies.
3. Or is there a reason XRootD is different from other packages?

I'll probably update this PR to not set it again in `sndsw.sh` though.

**Comment by olantwin** [comment]
I'll also test whether the setting of `XROOTD_ROOT` during the sndsw build is really necessary.

**Comment by ThomasRuf** [comment]
I think it was set in sndsw because I had not succeeded to have it set in xrootd.sh. It is true that on some systems, never understood the reason for it, one has to manually set XROOTD_ROOT. If you have a solution with fixes this, great!

**Comment by ThomasRuf** [comment]
One issue remains when changing xrootd.sh. We could run into a problem when there are changes to alibuild which require modifications to xroot.sh, we cannot just import it from alidist. Maybe this was the reason why I put the setting into sndsw.sh

**Comment by siilieva** [comment]
Perhaps the above is why we have ~ dozen env variables set in sndsw.sh - whatever the recipe(imported or customized) we make sure the variables needed in sndsw are set properly.

I believe if a package is needed during the build it will be listed in the required ones and the build will fail loudly(as opposed to quietly :D) if missing.

**Comment by olantwin** [comment]
> I believe if a package is needed during the build it will be listed in the required ones and the build will fail loudly(as opposed to quietly :D) if missing.

I've observed at least once that a package skips linking against a dependency quietly if its build system can't find it. While alibuild indeed complains if a dependency isn't there, that doesn't guarantee that a build uses it if it is!

**Comment by olantwin** [comment]
> I think it was set in sndsw because I had not succeeded to have it set in xrootd.sh. It is true that on some systems, never understood the reason for it, one has to manually set XROOTD_ROOT. If you have a solution with fixes this, great!

I already got it working by modifying the module file directly. Now I'm just waiting for ROOT and the rest of the stack to rebuild to confirm that the modified recipe works.

**Comment by olantwin** [comment]
> One issue remains when changing xrootd.sh. We could run into a problem when there are changes to alibuild which require modifications to xroot.sh, we cannot just import it from alidist. Maybe this was the reason why I put the setting into sndsw.sh

Merging the changes should be fairly straightforward. I volunteer to take care of any merge conflicts resulting from these changes.

**Comment by siilieva** [comment]
Then if your build go ok, we can merge these changes.

**Comment by ThomasRuf** [comment]
do you plan to rebuild the complete suite on cvmfs?

**Comment by olantwin** [comment]
> do you plan to rebuild the complete suite on cvmfs?

Don't think it's worth it for this change alone.
I'd suggest accumulating small fixes like this until we have something important enough to rebuild.

**Comment by siilieva** [comment]
@ThomasRuf  would you suggest it better to leave the request open and just before building a new stack, sometime in the future, review the all accumulated requests, merge them(if ok) and rebuild?

**Comment by olantwin** [comment]
> @ThomasRuf  would you suggest it better to leave the request open and just before building a new stack, sometime in the future, review the all accumulated requests, merge them(if ok) and rebuild?

What would be the benefit of postponing the merge until a rebuild is needed?

I only see disadvantages:

1. More changes to review all at once
2. Fixes don't benefit people building from scratch (architectures not on CVMFS, containers, experimentation)
3. Hard to judge which changes merit a rebuild or not before the changes are already reviewed.

**Comment by olantwin** [comment]
> @ThomasRuf  would you suggest it better to leave the request open and just before building a new stack, sometime in the future, review the all accumulated requests, merge them(if ok) and rebuild?

What would be the benefit of postponing the merge until a rebuild is needed?

I only see disadvantages:

1. More changes to review all at once
2. Fixes don't benefit people building from scratch (architectures not on CVMFS, containers, experimentation)
3. Hard to judge which changes merit a rebuild or not before the changes are already reviewed.

**Comment by olantwin** [comment]
The local build is complete and works (can run e.g. the simulation using an input file accessed via XRootD fine).

```
$ alienv printenv XRootD/latest-release
 Loading XRootD/latest-release
  Loading requirement: BASE/1.0
LD_LIBRARY_PATH=/home/olantwin/Projects/snd@lhc/sw/arch_x86-64/XRootD/v5.5.5-local4/lib; export LD_LIBRARY_PATH;
PATH=/home/olantwin/Projects/snd@lhc/sw/arch_x86-64/XRootD/v5.5.5-local4/bin:/home/olantwin/.local/bin:/home/olantwin/.config/emacs/bin:/home/olantwin/.miniconda/condabin:/usr/local/bin:/usr/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl; export PATH;
__MODULES_LMALTNAME=BASE/1.0\&as\|BASE/default\&as\|BASE/latest; export __MODULES_LMALTNAME;
__MODULES_LMPREREQ=XRootD/latest-release\&BASE/1.0; export __MODULES_LMPREREQ;
_LMFILES_=/home/olantwin/Projects/snd@lhc/sw/MODULES/arch_x86-64/BASE/1.0:/home/olantwin/Projects/snd@lhc/sw/MODULES/arch_x86-64/XRootD/latest-release; export _LMFILES_;
LOADEDMODULES=BASE/1.0:XRootD/latest-release; export LOADEDMODULES;
BASEDIR=/home/olantwin/Projects/snd@lhc/sw/arch_x86-64; export BASEDIR;
PYTHONPATH=/home/olantwin/Projects/snd@lhc/sw/arch_x86-64/XRootD/v5.5.5-local4/lib/python/site-packages; export PYTHONPATH;
XROOTD_ROOT=/home/olantwin/Projects/snd@lhc/sw/arch_x86-64/XRootD/v5.5.5-local4; export XROOTD_ROOT;
__MODULES_LMTAG=BASE/1.0\&auto-loaded; export __MODULES_LMTAG;
test 0;
```
```
$ alienv printenv sndsw/latest | grep XROOTD
Use alienv list to list loaded modules.
Loading sndsw/latest
  Loading requirement: BASE/1.0 XRootD/v5.5.5-local4 XercesC/v3.2.2-local1 GEANT4/v11.1.0-snd-local1
    lhapdf/lhapdf-6.5.3-snd-local1 boost/v1.75.0-local1 HepMC/v2.06.09-local1
    pythia/sndsw-pythia8309-local1 pythia6/v6.4.28-snd-local1 ROOT/v6-28-06-local2
    log4cpp/1b9f8f7c031d6947c7468d54bc1da4b2f414558d-local1 apfel/3.0.6-local1 GENIE/v3.2.0-local2
    Tauolapp/v1.1.5-ship-local2 PHOTOSPP/v3.61-local2 EvtGen/R01-06-00-ship-local2 fmt/7.1.0-local1
    FairLogger/v1.9.0-local1 asio/v1.19.1-local1 asiofi/v0.5.1-local1 FairMQ/v1.4.55-local1 VMC/v2-0-local2
    GEANT3/v4-1-local2 vgm/v5-0-snd-local2 GEANT4_VMC/v6-1-p2-snd-local2 FairRoot/v18.4.9-local2
    alpaca/v1.1-local1 FEDRA/rev1523-local2
XROOTD_ROOT=/home/olantwin/Projects/snd@lhc/sw/arch_x86-64/XRootD/v5.5.5-local4; export XROOTD_ROOT;
```

From my side this should be good to go now.

**Comment by ThomasRuf** [comment]
Just for curiosity, why do we have to make this modification to xrootd.sh while apparently it is not needed for ALICE?

**Comment by olantwin** [comment]
As far as I can tell, the only place this variable is used is in sndsw when setting the PYTHONPATH. Maybe we don't actually need it there.

**Comment by ThomasRuf** [comment]
now i remember, yes, we need it. Otherwise we don't have the xrootd python modules, see shipLHC/scripts
/Monitor.py, from XRootD.client.flags import DirListFlags, OpenFlags, MkDirFlags, QueryCode. Probably ALICE does not use the python modules.

**Comment by olantwin** [comment]
That makes sense. I think ALICE mostly uses C++, with very little python in the software framework.

**Review by siilieva — APPROVED** [review]
ok

**Pull request merged**
