### PR TITLE
sndsw: define FAIRSHIP and FAIRSHIP_HASH again

### PR DESCRIPTION
**Pull request by olantwin**
Fixes https://github.com/SND-LHC/sndsw/issues/19

### CODE REVIEW

**Review by ThomasRuf — APPROVED** [review]
The idea behind FAIRSHIP_HASH or SNDSW_HASH is to be able to store the hash in the geofile in order to trace back with which version the events were generated. Maybe we should add some logic into saveBasicParameters to know which hash to use.

**Comment by olantwin** [comment]
I wonder whether it would be better to ask `git` on the fly? As the python code can be modified without requiring a rebuild, this might be more reliable.

**Comment by ThomasRuf** [comment]
yes, but you need to know for which hash to ask for. In run_simScript or saveBasicParameters, how do I know that I need to save the hash for sndsw or FairShip?

**Comment by olantwin** [comment]
Currently `saveBasicParameters` is in a git repo when executed, right? It should be able to ask `git` for the hash of the current repo.

**Comment by ThomasRuf** [comment]
not sure what you mean. run_simScript.py is  usually not executed in a git repo. It will import saveBasicParameters which is in a git repo, but this does not help. Except, if one uses the file location:
saveBasicParameters.__file__
'/media/disk0/SNDBuild/sw/ubuntu2004_x86-64/sndsw/master-1/python/saveBasicParameters.py'

from this, go to  
/media/disk0/SNDBuild/sw/ubuntu2004_x86-64/sndsw/latest-master-release/.git/refs/heads/master 
3c37ef1ebf4b3f6097917753f302f49c49a2ccc4

needs some logic about which branch to take.

**Comment by olantwin** [comment]
I need to think about how to best do this. Indeed, we can't depend on being in a git repo at runtime.

In the medium term, maybe we can leverage aliBuild to get this information? It hashes all source repositories etc. to figure out whether things need building, so has the information we need to differentiate software versions (even when modifications are not committed). Currently this information isn't exposed through the tools though.

**Pull request merged**
