### PR TITLE
Update to GENIE v3.2, including changes for geometry driver and new high energy tunes

### PR DESCRIPTION
**Pull request by cvilelahep**
- GENIE:
   - Update to version 3.2.
     - Get code directly from GENIE official repository.
       - We can keep SND@LHC-specific GENIE configuration files in `sndsw`. I will prepare a pull request with this soon.
   - Disable:
     - NuMI interface, atmospheric neutrino interface, nucleon decay physics.
   - Enable: 
     - FNAL interface (needed for geometry driver), apfel interface (needed for new high energy tunes), boosted dark matter, heavy neutral lepton and "dark neutrino" BSM models.
 - apfel:
   - Required for GENIE new high energy tunes.
- ~~GENIE_HE_SF:~~
   - ~~High energy tunes need pre-calculated structure functions. Unfortunately GENIE looks for the them in the GENIE install directory so these need to be calculated during build time. Takes 10 minutes or so. We can find a way to do this after building the software, but it will require someone with write permissions to copy them to the GENIE install directory.~~
 - lhapdf:
   - Downloading a couple of extra PDFs for GENIE high energy tune.
 - sndsw:
   - ~~Add GENIE_HE_SF as a requirement.~~
     - ~~This triggers the pre-calculation of the structure functions for the GENIE high energy tunes.~~
   - Set GALGCONF environment variable to point to `$SNDSW_ROOT/shipgen/genie_config`. This is where I'll add the GENIE model configuration files for SND@LHC.
 - defaults_release:
   - Updated GENIE version
   - Added log4cpp
   - ~~Added GENIE_HE_SF~~
   - Fixed typo in lhapdf

### CODE REVIEW

**Review by ThomasRuf — COMMENTED** [review]
This part, "Unfortunately GENIE looks for the them in the GENIE install directory so these need to be calculated during build time. ", I do not understand. Is this because on lxplus, the install directory is on CVMFS? 
Are these pre-calculated structure functions valid for the lifetime of a release? Or change from time to time?

**Comment by cvilelahep** [comment]
The reason for this hack was that I initially thought the path to the structure functions was hard-coded to be inside the `$GENIE` directory tree, [here](https://github.com/GENIE-MC/Generator/blob/1e1298603228af6302b8b0831d6e1fb45bc0429f/src/Physics/HEDIS/XSection/HEDISStrucFunc.cxx#L52).

However, I just realized there is an (undocumented) option to set the path in one of the xml configuration files. It's still not ideal, but at least it makes it possible deal with the structure functions in the `sndsw` package (where the xml config files will live) instead of `snddist`, where they definitely do not belong.

I'll remove `GENIE_HE_SF` from this PR.

**Review by ThomasRuf — APPROVED** [review]
ok.

**Comment by ThomasRuf** [comment]
For the new entry apfel, do we have a check that it will be taken from the system(CVMFS) when available?

**Comment by ThomasRuf** [comment]
I guess we need something like this in defaults-release.sh:
  apfel:    
    tag: 3.0.6
    prefer_system_check: |
      ls $APFEL_ROOT/bin > /dev/null && \
      ls $APFEL_ROOT/lib > /dev/null && \
      ls $APFEL_ROOT/include > /dev/null && \
      true

**Comment by cvilelahep** [comment]
Yes, of course -- sorry I missed this. I added it in #23.

**Pull request merged**
