### PR TITLE
Load dependencies only when available (!=CVMFS)

### PR DESCRIPTION
**Pull request by olantwin**
Fixes your issue, @dcentanni

### CODE REVIEW

**Review by siilieva — COMMENTED** [review]
would this work with the genfit solution we have in sndsw or only with the standalone solution you use for AdvSND?

**Comment by olantwin** [comment]
> would this work with the genfit solution we have in sndsw or only with the standalone solution you use for AdvSND?

In fact, this *only* works or the builtin Genfit used by sndsw and advsndsw. When using external genfit, many other changes are necessary, which are neither in advsndsw nor snddist master branches.

**Review by siilieva — APPROVED** [review]
Ok then, lets proceed to merge

**Comment by olantwin** [comment]
For external genfit, maybe we want to add a second default, but having it in a separate branch also works for now.

**Pull request merged**
